apiVersion: v1
kind: Namespace
metadata:
  name: inferscale-system
  labels:
    app.kubernetes.io/part-of: inferscale
    inferscale.io/control-plane: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
