apiVersion: v1
kind: ServiceAccount
metadata:
  name: inferscale-api
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inferscale-controller
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inferscale-admission
automountServiceAccountToken: false
