version: "2"
run:
  timeout: 5m
linters:
  default: standard
  enable:
    - errorlint
    - exhaustive
    - govet
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
formatters:
  enable:
    - gofmt
    - goimports
