apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - storage-secret.yaml
configMapGenerator:
  - name: inferscale-config
    namespace: inferscale-system
    behavior: merge
    literals:
      - INFERSCALE_ENV=local-wsl
      - INFERSCALE_LOG_LEVEL=debug
      - INFERSCALE_FAKE_RUNTIME=true
generatorOptions:
  disableNameSuffixHash: true
